### ISSUE TITLE
Is that right example?

### ISSUE THREAD

**Issue by artsiom-loika** [kumabook/FeedlyKit#10]
Im trying to connect use that example, but without success
Can you help me?
`let streamId = "feed/http://fapl.ru/rss.xml"
  var paginationParams = PaginationParams()
  let client = CloudAPIClient(target: .Sandbox)
  let accessToken = "My token"
  client.setAccessToken(accessToken)

  client.fetchContents(streamId,
       paginationParams: paginationParams,
       completionHandler: { (response) -> Void in
       debugPrint(response)
  })`

**Comment by kumabook** [comment]
Hi,
thank you for your feedback.

I think the request is canceled, because `client` is not strongly referenced.
So, the client object is released and also the request is canceled after leaving the scope.

I think you should have strong reference of `CloudAPIClient` instance (`client`) or Request

For example, Add `CloudAPIClient` property to ViewController or some other classes.

```
class ViewController: UITableViewController {
    private let reuseIdentifier = "UITableViewCell"
    private let feedUrl         = "feed/https://news.ycombinator.com/rss"
    private let apiClient       = CloudAPIClient(target: .Production)
```

Also, refer to https://github.com/kumabook/FeedlyKit/blob/master/Example/FeedlyKitExample/ViewController.swift

**Comment by artsiom-loika** [comment]
Thanks man! It working!

**Comment by kumabook** [comment]
:+1:
